# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-Sample

  target 'SwiftUI-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUI-SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
